"""
Django settings for mbasql project.

Generated by 'django-admin startproject' using Django 1.9.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EXPLORER_CONNECTIONS = {'default': 'default'}
EXPLORER_DEFAULT_CONNECTION = 'default'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qdq4g2c0#ir=q(s6hc%a4^31(e5f)nh@8*5r&75&)65*%hx4&q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ['*']
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'explorer',
    'shop',
    'sorl.thumbnail',
]

MIDDLEWARE = [
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'mbasql.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.in_cart_context',
                'shop.context_processors.class_settings_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'mbasql.wsgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/home/afterskills/production/mbasql/media/cache',
    }
}


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


DATABASES = {
    'default': {
        'NAME': 'afterskills$mbasql',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'afterskills',
        'PASSWORD': 'rickandmorty2019',
        'HOST': 'afterskills.mysql.pythonanywhere-services.com',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
        'OPTIONS': {
          'autocommit': True,
          'init_command': "SET default_storage_engine=MyISAM",

        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = u'/home/afterskills/production/mbasql/media'
MEDIA_URL = '/media/'
STATIC_ROOT = u'/home/afterskills/production/mbasql/static'
STATIC_URL = '/static/'

#GMAIL SETTINGS:  works great
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'novohunt.email_backend.DKIMBackend'
DKIM_SELECTOR = ''
DKIM_DOMAIN = 'mbasql.com'
DKIM_PRIVATE_KEY = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCkfMIICXQIBAAKBgQDbzo/OHKT4DfYC2hdgw7K46Rg/iXthTDnYW6VIoqErn8KNqM3U0uOKqrPjUnefG/k6o8wPzs1Kb59ddiPRVxh9A9f4Rf9aztEJbGq4vAcKi0N/UGCmuujmGS9UnNgQbwxvIq8xJ3bidEQTy0MemiSogN7zrDPsgyEuUW7pc28dxQIDAQABAoGAeq8BPtZoEXehXxghQkYYY/LeMOBod/cWtjb4uuDiujmSWoTkVaxbilMa0n99+tWfNuajiBMyLCC/P2goN7i4Fk1ipTAq2JONWhHNWOr2UOQSe0GOst6orSCqYinJ+bfnSo/ZGV2ZSqhjmbaOnzKWeT7jpOQ5cpp2O3C4BsucJYUCQQD/O2+pJXU90jK3KhVhaPCqSn4jvwGcAu5/StSwRwmaJt4G6bBBqAdoBXa1GGizBmAbvKkfh3kUPuE6uvtUO8O3AkEA3HfX3ZgyNjQpzsfBC/H60QcBos8ssbIzTarzqjgicRcgl4BSQu7i39ujr2QJk3W84/EEFP78bGTGmtiiS40CYwJBAIBdo0Yd+b5S9oDaoJAyWEA9YP2XdjbB3rOUri3OPI0UGTy+0Y/j832kqdRg51+KyFGK7EBYQVQmX97K5dayjDcCQEZeYiIyj+RJJgcALxfW9o19RQJoSgW1sTZbGEb+f8/E5/wzUw5WHUgCXO6AaaYNcGr45Kqm8H7Qc6u89aBTs60CQQDXR2iPtuvOWGWsRbES20Lw0F/XC82PEGtWq7qCbZROzEgm6jlEYTc6s3nT1YESCT0sWgeQQO6GEYiIDCAE/OGe'
DEFAULT_FROM_EMAIL = 'hello@mbasql.com'
EMAIL_HOST = 'mail.mbasql.com'
EMAIL_HOST_USER = 'hello@mbasql.com'
EMAIL_HOST_PASSWORD = 'weldonmarafi'
EMAIL_PORT = 587
EMAIL_USE_TLS = True



EXPLORER_PERMISSION_VIEW = lambda u: u.is_active
EXPLORER_PERMISSION_CHANGE	= lambda u: u.is_active
EXPLORER_SCHEMA_EXCLUDE_TABLE_PREFIXES = ('django.contrib.auth', 'thumbnail','sorl.thumbnail','django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.admin','explorer')
EXPLORER_SQL_BLACKLIST = ('ALTER', 'RENAME ', 'DROP', 'TRUNCATE', 'INSERT INTO', 'UPDATE', 'REPLACE', 'DELETE', 'ALTER', 'CREATE TABLE', 'SCHEMA', 'GRANT', 'OWNER TO','SHOW')
